### ISSUE TITLE
is there a way to add tabs to the web without doing it within docker?

### ISSUE THREAD

**Issue by eelucio** [FREVA-CLINT/freva-web#16]
in the new freva-web server release I realised that my "help" tab dissapeared and at the same time the web menu:
```toml
MENU_ENTRIES = [
    ["Plugins", "plugins:home", "plugin_menu"],
    ["Data-Browser", "solr:data_browser", "browser_menu"],
    ["Result-Browser", "history:result_browser", "result_browser_menu"],
    ["History", "history:history", "history_menu"],
    [ "Help",  "plugins:about", "doc_menu",], <---
]
```
was no longer active nor possible at the `freva_web_conf.toml`

I had to go in the docker container and add manually that key:val at `/opt/freva_web/django_evaluation/settings/local.py`:

```python
_MENU_ENTRIES = [
    ["Plugins", "plugins:home", "plugin_menu"],
    ["Data-Browser", "solr:data_browser", "browser_menu"],
    ["Result-Browser", "history:result_browser", "result_browser_menu"],
    ["History", "history:history", "history_menu"],
    [ "Help",  "plugins:about", "doc_menu",], <---
]

```

But I know that ideally I should not tinker with a container for things like that.

**Comment by antarcticrainforest** [comment]
Actually, the system is behaving as it's supposed to. You deleted (possibly without intention) the `menu_entries` from the config file.

**Comment by antarcticrainforest** [comment]
```
cat /work/bm1159/XCES/freva/web/freva_web_conf.toml|grep -i menu

```

while

```
cat /work/ch1187/clint/freva-dev/freva/web/freva_web_conf.toml|grep -i menu
MENU_ENTRIES = [ [ "Data-Browser", "solr:data_browser", "browser_menu",], [ "Plugins", "plugins:home", "plugin_menu",], [ "History", "history:history", "history_menu",], [ "Result-Browser", "history:result_browser", "result_browser_menu",], [ "Help", "plugins:about", "doc_menu",],]
```

In short you can already configure the tabs from "outside" the docker. I suspect that you deleted this entry in the deployment config. 

The default by the deployment should add the menu entries:

https://github.com/FREVA-CLINT/freva-deployment/blob/main/assets/config/inventory.toml

**Comment by eelucio** [comment]
you are totally right, I deleted by accident in the deployment and when I added it on Friday was throwing me an 503 error. BUT I must have had an error in the dictionary as when trying to reproduce it right now it was working fine.
