### ISSUE TITLE
is freva_web pointing to the right submodule?

### ISSUE THREAD

**Issue by eelucio** [FREVA-CLINT/freva-web#17]
When git recursively cloning this repo I realised that freva_web is is pointing to 
https://github.com/FREVA-CLINT/freva-service-config/tree/6ea79f0b091ba714c51067cf70ee614e77b341a9

while freva-core is pointing to
https://github.com/FREVA-CLINT/freva-service-config/tree/5dad019aae32ecba719506ddf3d83764c4f93900

here the managed-schema.xml differs (at least)

**Comment by antarcticrainforest** [comment]
That should not matter for the production system, but for the dev system.  @Karinon

**Comment by Karinon** [comment]
I have updated it now

**Comment by antarcticrainforest** [comment]
(y)
